name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - LICENSE
      - .github/workflows/*.yml
    tags-ignore:
      - '**'
  pull_request:
    branches: [ master ]

jobs:

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.15.x
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run linters
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: v1.29

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Check out code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./... -covermode=count

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage
      run: |
        go test ./... -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  build:
    needs: [test, coverage]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        GOOS=darwin GOARCH=amd64 go build -o bin/go-cardano-client-darwin-amd64 cmd/cli/main.go
        GOOS=linux GOARCH=amd64 go build -o bin/go-cardano-client-linux-amd64 cmd/cli/main.go
        GOOS=windows GOARCH=amd64 go build -o bin/go-cardano-client-windows-amd64.exe cmd/cli/main.go
